name: Publish on Version Change
on:
  push:
    paths:
      - 'packages/pieces/**/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # Copy the .npmrc file to the home directory
    - name: Configure npm
      run: echo "@activepieces:registry=https://registry.npmjs.org/" >> ~/.npmrc
           echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
           echo "legacy-peer-deps=true" >> ~/.npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Your custom script
    - name: Run custom script
      run: ./scripts/check-version-and-publish.sh
