name: Publish on Version Change
on:
  push:
    paths:
      - 'packages/pieces/**/package.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch entire history to enable comparison

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Set execute permissions on script
        run: chmod +x ./scripts/check-version-and-publish.sh

      - name: Check Version Changes and Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./scripts/check-version-and-publish.sh
